// <auto-generated />
namespace ReceptDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Deletetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Deletetable));
        
        string IMigrationMetadata.Id
        {
            get { return "202103281825093_Delete table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
